baseURL = "http://www.example.com/"
languageCode = "en"
theme = "ghazal"

[outputs]
  home = ["HTML"]
  page = ["HTML"]

[params]
    title = "ghazal Theme"
    author = "Darshan Baral"
    description = "A hugo theme for personal blogs"
    footer = "2020 Darshan Baral."
    shortAbout = "This is a short intro about me to describe some of the cool things I do."
    mainimage = "https://i.stack.imgur.com/oI2SB.jpg?s=328&g=1"
    profileImage = "https://i.stack.imgur.com/oI2SB.jpg?s=328&g=1"

    [params.theme]
        fontSize = "20px"
        dateFormat = "2006/01/02"
        paginateNum = 5

    [params.social]
        github = "#"
        twitter = "#"
        linkedin = "#"
        email= "#"
